# Generated by Django 3.1.7 on 2021-05-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_number', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=120, unique=True)),
                ('balance', models.FloatField(default=50)),
            ],
        ),
    ]
